name: "UTBot code analysis"
description: "UTBot code analysis allows adding tests and code analysis information by pull request"
branding:
  icon: 'terminal'
  color: 'blue'

on:
  inputs:
    add_tests:
      description: 'Do tests need to be pushed'
      required: true
    refresh_tests:
      description: 'Do old tests need to be deleted'
      required: true
    utbot_version:
      description: 'UTBot version'
      required: true
    scope:
      description: 'Run utbot to all project, directory or file'
      required: true
    path:
      description: 'directory or file name'
      required: true
    
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2  

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: codeAnalysis/project_code_analysis.sarif
